global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'news-aggregator-api'
    static_configs:
      - targets: ['api-gateway:9090']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'news-aggregator-collector'
    static_configs:
      - targets: ['data-collector:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'news-aggregator-processor'
    static_configs:
      - targets: ['processor:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
